FROM nginx:1.13-alpine

ADD vhost.conf /etc/nginx/conf.d/default.conf

WORKDIR /var/www

COPY public /var/www/public

RUN mkdir -p /var/www/storage/app/public

RUN ln -snf /var/www/storage/app/public public/storage